export const data = [
  {
    field: 1,
    tag: "input",
    type: "text",
    value: "",
    id: "username",
    name: "username",
    label: "Username",
    errormsg: "",
    isErrorShown: false,
  },
  {
    field: 2,
    tag: "input",
    type: "email",
    value: "",
    id: "email",
    name: "email",
    label: "Email",
    errormsg: "",
    isErrorShown: false,
  },
  {
    field: 3,
    tag: "input",
    type: "text",
    value: "",
    id: "password",
    name: "password",
    label: "Password",
    errormsg: "",
    isErrorShown: false,
  },
];

export const loginData = [
  {
    field: 1,
    tag: "input",
    type: "email",
    value: "",
    id: "email",
    name: "email",
    label: "Email",
    errormsg: "",
    isErrorShown: false,
  },
  {
    field: 2,
    tag: "input",
    type: "text",
    value: "",
    id: "password",
    name: "password",
    label: "Password",
    errormsg: "",
    isErrorShown: false,
  },
];
